# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirstPhaseByRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirstPhaseByRxSwift
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
  # add the Firebase pod for Google Analytics
    pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
    pod 'Firebase/Firestore'
    pod 'Firebase/Functions'
    pod 'FirebaseFirestoreSwift'
    pod 'Firebase/Core'
    pod 'Firebase/Crashlytics'

  target 'FirstPhaseByRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'

  end

  target 'FirstPhaseByRxSwiftUITests' do
    # Pods for testing
  end

end
